name: SonarQube Local Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=demo-project
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Wait for Sonar processing
        run: sleep 10

      - name: Check Quality Gate
        run: |
          STATUS=$(curl -s "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=demo-project" \
          -u "$SONAR_TOKEN:" | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $STATUS"

          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate Failed"
            exit 1
          fi